data_engineer:
  - "data engineer"
  - "data solutions developer"

software_engineer:
  - "software engineer"
  - "software developer"
  - "softwareentwickler"
  - "full stack"
  - "web application developer"
  - "web developer"
  - ".net developer"
  - "front end developer"
  - "salesforce developer"
  - "release train engineer"
  - "staff product engineer"
  - "development engineer"

data_scientist:
  - "data scientist"

it_specialist:
  - "it specialist"
  - "it spec"
  - "itspec"
  - "information technology specialist"

cybersecurity:
  - "cybersecurity"
  - "infosec"
  - "security engineer"
  - "penetration tester"
  - "security manager"

cloud_infrastructure:
  - "cloud engineer"
  - "infrastructure engineer"
  - "systems administrator"
  - "network architect"
  - "network engineer"
  - "cloud solutions engineer"

systems_engineer:
  - "systems engineer"
  - "site reliability"
  - "sre"

data_analyst_bi:
  - "business intelligence"
  - "data analyst"

architect:
  - "solutions architect"
  - "enterprise architect"
  - "cloud architect"
  - "lead architect"
  - "principal engineer"

developer_other:
  - "python developer"
  - "java"
  - "cobol developer"
  - "kafka engineer"
  - "test automation"

platform_engineer:
  - "platform engineer"
  - "platform engineering"

qa_engineer:
  - "qa automation engineer"
  - "test engineer"
  - "automation engineer"